// This file is auto generated by CMake
#pragma once

// The absolute path to the root of the repository.
#ifndef KSCORE_TEST_DATA_DIR
#define KSCORE_TEST_DATA_DIR "/Users/mjb/repos/kslice/testfiles"
#endif

// The absolute path to the binary output directory.
#ifndef KSCORE_BINARY_OUTPUT_PATH
#define KSCORE_BINARY_OUTPUT_PATH "/Users/mjb/repos/kslice/cmake-build-debug"
#endif